project: coconut
save_path: PATH_TO_SAVE_THE_MODEL
name: gsm-coconut-eval

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
load_model_path: PATH_TO_COCONUT_CHECKPOINT
model_config_path: PATH_TO_GPT2_CONFIG
seed: 0
resume: 15
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_test.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01
